### ISSUE TITLE
What exactly should be in the export CSV?

### ISSUE THREAD

**Issue by iainbryson** [dtu-compute/dtu-quiz#7] opened 2016-02-18 14:20 UTC
The current spec seems to have a placeholder for these details.  

My assumption now would be that it's supposed to be something like:

Student Name, Student ID, Quiz ID, Submission ID, Total Correct, Total Incorrect, Time Used, Hints Used, Hints Remaining, Time Handed In

Fair?

Here's the document:

Export creates a CSV file of the results for the quiz and opens a Save dialog box. The purpose of the CSV file is for the admin to extract how each student have done in the quiz.

The format should be something similar to

xxxxxxxxxxx

**Comment by dtu-compute** [comment] 2016-02-18 16:19
We will need a format, where we can read the state for each question in the quiz. The professors will most likely analyse the csv file in R, and it would be great if the csv format doesn't change between quizzes, so e.g. the R script can be used on any quiz.

I would imagine something like:

Meta Quiz ID,
Meta Quiz Title,
Meta Quiz Start,
Meta Quiz Finish,
Meta Quiz Fullscreen,
Meta Quiz Attempts Total,
Meta Quiz Max Time,
Meta Quiz Total Number of Questions,

Student Name,
Student ID,
Student Belongs to Class,

Quiz Submission ID,
Quiz UserAgent Strings Seen,
Quiz Student IP Addresses Seen,
Quiz Attempt Number,
Quiz Time Used,
Quiz Time Handed In
Quiz Left Fullscreen date and time,
Quiz Returned to Fullscreen date and time,

Question Number,
Question Type,
Question Students Answer,
Question Is Correct,
Question Is Reviewed,
Question Last Modified on client,
Question Hints Used,
Question Hints Total

The format is super ineffective, as the first 3 sections will be repeated for each question.

One thing I am sure the professors will mine this for, is to figure out the difficultly level of each question.

"Question Students Answer" will be inparticular interesting to radio botton questions, as they then
can do statistics on how many that choose e.g. number 4.

Let me just get it confirmed that this is the format they want.

**Comment by iainbryson** [comment] 2016-02-18 19:40
Thanks Martin!

Most of this is straightforward. Here are the parts that are more complicated:

* IP/UserAgents.  Right now I'm not collecting these.  Do you want me to add a work item to being to do so?  If you want to include a list, how do they get embedded into a column of the csv?  Is there a limit to the number of each of these which you want captured for a given submission?
* Left/Returned to fullscreen.  There will be many of these per quiz submission and it's not something which is currently tracked.  So as above, do you want to start tracking this and, if so, how should this be encoded in the csv?

Thanks!

**Comment by dtu-compute** [comment] 2016-02-18 20:05
I have asked for a meeting to talk with him about the format, and what he think is important. Perhaps we end up with yaml instead of csv. I am not sure at this point.

Let's wait collecting IP/UserAgents until he have approved it, but my idea were that each of them should be an array, in case the student e.g. changes computer or network connection. But let's see what he says =)

Yes, tracking when fullscreen is entered and exited is important for quizzes where the student is not allowed to use any aids. Ideally if a quiz is created to be in full screen mode, then it should not be exited, but let's say the student hits Esc by mistake, and then enters fullscreen again after 10 seconds, then it would be good to have this info, as it is unlikely the student have been able to Google anything in just 10 seconds.

My idea were that the csv is generated when the professor clicks "Export to CSV".

Was that what you were asking about?

**Comment by dtu-compute** [comment] 2016-02-19 10:47
Ok, so we would like to go with a yaml file which contains the following info. Some of the names are not optimal, so fell free to rename those you like.

What do you think?

```
Meta Quiz ID,
Meta Course,
Meta Quiz Title,
Meta Quiz Start,
Meta Quiz Finish,
Meta Quiz Fullscreen,
Meta Quiz Attempts Total,
Meta Quiz Max Time,
Meta Quiz Total Number of Questions,

Student Name,
Student ID,
Student Belongs to Class:

Quiz Submission ID,
Quiz UserAgent Strings Seen,
Quiz Student IP Addresses Seen,
Quiz Attempt Number,
Quiz Time Begin, ## updated compared to previous post I made in Github. Was: Quiz Time Used
Quiz Time Handed In
Quiz Left Fullscreen date and time,
Quiz Returned to Fullscreen date and time,

Question Number,
Question Type,
Question Students Answer,
Question Is Correct,
Question Is Reviewed,
Question Last Modified on client,
Question Hints Used,
Question Hints Total 
```

**Comment by iainbryson** [comment] 2016-02-25 04:42
Hi Martin,

Some questions on this:
(1) I assume this is a hierarchical format since we moved to yaml.  is that right?
(2) Can you note which of these are arrays?  i.e. I assume "left fullscreen date and time" are arrays, but want to be sure
(3) What exactly goes in Student's Answer?  Is this the entire answer for any question type? i.e. "A, C,B" for all that apply, the full text of a free text question, the individual segments of text for the fill in the blank questions?  and what about drawing questions?
(4) Question is Reviewed: Does it apply only to manually reviewed questions?

Thanks!

**Comment by dtu-compute** [comment] 2016-02-25 09:56
1: Yes, as much of the info doesn't change, it would be a waist and make it harder to parse if everything had to be repeated for each question in a csv file. So the meta section would only appear once in the yaml file, as it is global for the quiz. Then I imagine a nested hash structure where "Quiz Submission ID" is the primary key.

2: These should be arrays:
* Quiz UserAgent Strings Seen
* Quiz Student IP Addresses Seen
* Quiz Left Fullscreen date and time
* Quiz Returned to Fullscreen date and time
* Question Students Answer (because of Fill in the blank this have to be an array I suppose)

3: yes, the full answer please. For drawing set it to "N/A" for now. Perhaps for the 2017 version would it make sense to perhaps have links to the drawings so external scripts can mine them.

4: yes, so for all other questions this should be N/A. A good point actually. For Fill in theblank, free text, and drawings then until Question Is Reviewed, then Question Is Correct have to be N/A or similar as a way to protect the professors from calculating a grade until Question Is Reviewed is true.

And names I have given them doesn't have to be the once that end up in the yaml file. Please reformulate where it makes sense.

**Closed** 2016-04-17 15:26 UTC
