### ISSUE TITLE
Failed to create quiz template for cloned quiz!

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#78] opened 2016-04-13 11:38 UTC
is an error message in `app/services/clone_quiz_service.rb`

What does this error mean?

When an admin gets this, what can he do to fix the situation?

I think he got this error when he clicked many times on Clone.

**Comment by iainbryson** [comment] 2016-04-13 12:17
It’s most likely caused by a failure to save the new quiz.  Is this in the latest devel builds?  I haven’t deployed them anywhere but IIRC clone_quiz_service is newly-merged today. 

The best thing to do for these cases is to send along the logs.   I’m actually considering adding a button to send the logs whenever something odd happens.  NewRelic has similar functionality we could also use.

**Comment by dtu-compute** [comment] 2016-04-13 12:43
He got this error either in the weekend or Monday. Can't remember.

That's a great idea with the logs. I am not familiar with NewRelic's way of doing this. Is it a feature that they offer?

**Comment by iainbryson** [comment] 2016-04-13 14:22
Do you have a mail server config I can use for SMTP?  I have everything hooked up, but now I need to send the mails.

**Comment by dtu-compute** [comment] 2016-04-14 12:51
We don't have one that is suited for this, but perhaps I can work something out.

I'll get back when checked.

**Closed** 2016-04-19 04:49 UTC
Labels: enhancement

**Comment by dtu-compute** [comment] 2016-04-19 13:11
Our SMTP won't accept emails from the outside, so what I would really like instead is if critical errors (like this one) could be logged in one file, warn errors in another (if we have such?), and info (if we have such?) in another.

That way it will be easy to set up an alert in either [Monit](https://mmonit.com/monit/) or [LogStash](https://www.elastic.co/products/logstash). Monit is similar to Nagios. It can execute Bash scripts and take action based on its return code.
