### ISSUE TITLE
Perserve question order in json file

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#180] opened 2016-06-27 14:38 UTC
The column "Question Students Answer" in the json file, shows which answer the student gave for a particular question. E.g. in a multiple choice question.

But if the `randomize true` have been used for that question, the order of the answer options have been randomized, and there is no way to figure out what the order actually was for that student.

So to solve this, could the order in the json file be the same as in the `.quiz` file?

**Comment by iainbryson** [comment] 2016-09-17 17:04
I believe this was a duplicate of some another issue.

**Closed by iainbryson** 2016-09-17 17:04 UTC
Labels: 2016, enhancement, low
