### ISSUE TITLE
Wrong max time in Q1501

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#137] opened 2016-05-09 14:47 UTC
It said there was 1 hour and 5 minutes left, even though there was much less to 15:45 which was the end time.

**Comment by dtu-compute** [comment] 2016-05-13 12:48
Max time were set to unlimited and the end time were set so the students had 1 hour. For a hand full of students the timer wend down to 54 minutes, and then stayed there. Reloading the page updated the timer, but it was with a wrong time left.

**Comment by iainbryson** [comment] 2017-02-08 16:06
Cannot reproduce this, so closing.

**Closed by iainbryson** 2017-02-08 16:06 UTC
Labels: bug, critical
